PepuxFront/Controllers/ControlpanelController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Timers;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using PepuxFront.IpServiceLink;
using PepuxFront.Models;
using Timer = System.Timers.Timer;

namespace PepuxFront.Controllers
{
    public class ControlpanelController : Controller
        
    {      
        // GET: Chat
        public ActionResult Control(string confname, string dispname)
        {
            ViewData["confnm"] = confname;
            ViewData["dispnm"] = dispname;
            DatabsDataContext db = new DatabsDataContext();
            var virtvmid = db.VmrAliases.FirstOrDefault(v => v.alias == confname);
            var virtvmr = db.AllVmrs.FirstOrDefault(v => v.Id == virtvmid.vmid);
            string pinc = virtvmr.pin;
            ViewData["pinc"] = pinc;
            return View();
        }
        public ActionResult Index()
        {
            Timer renew = new Timer();
            renew.Interval = 3000;
            renew.Enabled = true;
            renew.AutoReset = true;
            renew.Elapsed += new ElapsedEventHandler(OnTimedEvent);
            return View();
        }
        private  void OnTimedEvent(object source, ElapsedEventArgs e)
        {
            GetData();
        }
        public ActionResult ActiveConf_Read([DataSourceRequest]DataSourceRequest request)
        {
            using (var allconfs = new PServiceClient())
            {

                IQueryable<ActiveConfs> confs = allconfs.GetActiveConfs().AsQueryable();

                DataSourceResult result = confs.ToDataSourceResult(request);

                return Json(result, JsonRequestBehavior.AllowGet);
            }

        }
        private IEnumerable<ActiveConfs> GetData()
        {
            IpServiceLink.PServiceClient obj = new PServiceClient();
            var data = obj.GetActiveConfs();

            return data;
        }
    }
}

PepuxFront/Views/Controlpanel/Index.cshtml
@using System.ServiceModel.Configuration
@using Microsoft.Ajax.Utilities
@using PepuxFront.Controllers
@using PepuxFront.IpServiceLink
@model PepuxFront.IpServiceLink.ActiveConfs

<div class="control_grid">
    <table id="table_ac" class="display">
        <thead>
            <tr>
                <th>Имя виртуальной переговорной комнаты</th>
                <th>Дата начала мероприятия</th>
                <th>Блокировка мероприятия</th>
                <th>Участники</th>
                <th>Управление</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
<div id="popup_block" class="hide">
    <div id="popup_content" class="b-popup b-popup-content">
        <table id="table_ap">
            <thead>
                <tr>
                    <th>Ведущий</th>
                    <th>Качество</th>
                    <th>Вх./исх.</th>
                    <th>Время подкл.</th>
                    <th>Имя</th>
                    <th>Протокол</th>
                    <th>Медиа-поток</th>
                    <th>Микрофон</th>
                    <th>Презентует</th>
                    <th>Стримит</th>
                    <th>IP-адрес</th>
                    <th>IP-порт</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    var oActConfTable = null;
    var oActPartTable = null;
    var confParts = false;
    var confName = 0;
    function refresh() {
        if (oActConfTable != null)
            oActConfTable.ajax.reload();
    }
    setInterval("refresh()", 30000);

    var uname = '@AccountController.Uname';

    $(document).ready(function() {
        oActConfTable = $('#table_ac').DataTable({
            "ordering": false,
            "searching": true,
            "paging": true,
            "autoWidth": false,
            "processing": true,
            "lengthChange": false,

            "serverSide": true,
            "ajax": {
                "type": "POST",
                "url": "/Admin/ActiveConf_Ajax",
                "contentType": 'application/json; charset=utf-8',
                "data": function(data) { return data = JSON.stringify(data); }
            },

            "columns": [
                { "data": "name" },
                { "data": "start_time2", "searchable": false },
                { "searchable": false },
                { "searchable": false },
                { "searchable": false }
            ],
            "columnDefs": [
                {
                    "targets": -3,
                    "data": "is_locked",
                    "render": function (data) {
                        if (data) {
                            return '<div class="fa fa-lock fa-fw brand-color"></div>';
                        } else {
                            return '<div class="fa fa-unlock fa-fw brand-color"></div>';
                        } 
                    }
                },
                {
                    "targets": -2,
                    "data": "name",
                    "render": function() {
                        return '<div><a href="#" onclick="javascript:confParts=true">Участники</a></div>';
                    }
                },
                {
                    "targets": -1,
                    "data": "name",
                    "render": function(data) {
                        return '<a href="Controlpanel/Control?confname=' + data + '&dispname=' + uname + '">Управление</a>';
                    }
                },
            ],

            "language": {
                "processing": "Подождите...",
                "search": "Поиск:",
                "lengthMenu": "Показать _MENU_ записей",
                "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
                "infoEmpty": "Записи с 0 до 0 из 0 записей",
                "infoFiltered": "(отфильтровано из _MAX_ записей)",
                "infoPostFix": "",
                "loadingRecords": "Загрузка записей...",
                "zeroRecords": "Записи отсутствуют.",
                "emptyTable": "В таблице отсутствуют данные",
                "paginate": {
                    "first": "Первая",
                    "previous": "Предыдущая",
                    "next": "Следующая",
                    "last": "Последняя"
                },
                "aria": {
                    "sortAscending": ": активировать для сортировки столбца по возрастанию",
                    "sortDescending": ": активировать для сортировки столбца по убыванию"
                }
            },
            "order": [[0, 'asc']],
            "pageLength": 10,
        });
    });

    $(document).on("click", function (e) {
        if (!$("#popup_content").is(e.target) && $("#popup_content").has(e.target).length == 0) {
            document.getElementById("popup_block").className = "hide";
            if (oActPartTable != null)
                oActPartTable.destroy();
        }
    });

    $('#table_ac tbody').on('click', 'td', function() {
        if (confParts) {
            confParts = false;
            confName = oActConfTable.cell(this).data();
            event.stopPropagation();
            document.getElementById("popup_block").className = "b-popup";

            oActPartTable = $('#table_ap').DataTable({
                "ordering": false,
                "searching": true,
                "paging": true,
                "autoWidth": false,
                "processing": true,
                "lengthChange": false,

                "serverSide": true,
                "ajax": {
                    "type": "POST",
                    "url": "/Admin/ActiveParts_Ajax?Confname=" + confName + "",
                    "contentType": 'application/json; charset=utf-8',
                    "data": function(data) { return data = JSON.stringify(data); }
                },

                "columns": [
                    { "searchable": false },
                    { "data": "bandwidth", "searchable": false },
                    { "searchable": false },
                    { "data": "connect_time", "searchable": false },
                    { "data": "display_name", "searchable": true },
                    { "data": "protocol", "searchable": false },
                    { "searchable": false },
                    { "searchable": false },
                    { "searchable": false },
                    { "searchable": false },
                    { "data": "remote_address", "searchable": false },
                    { "data": "remote_port", "searchable": false },
                ],

                "columnDefs": [
                {
                    "targets": 0,
                    "data": "role",
                    "render": function (data) {
                        if (data == 'chair') {
                            return '<div class="fa fa-check fa-fw green"></div>';
                        } else {
                            return '<div class="fa fa-times fa-fw red"></div>';
                        } 
                    }
                },
                {
                    "targets": 2,
                    "data": "call_direction",
                    "render": function (data) {
                        if (data == 'in') {
                            return '<div class="fa fa-arrow-down fa-fw brand-color"></div>';
                        } else {
                            return '<div class="fa fa-arrow-up fa-fw brand-color"></div>';
                        }
                    }
                },
                {
                    "targets": 6,
                    "data": "has_media",
                    "render": function (data) {
                        if (data) {
                            return '<div class="fa fa-check fa-fw green"></div>';
                        } else {
                            return '<div class="fa fa-times fa-fw red"></div>';
                        } 
                    }
                },
                {
                    "targets": 7,
                    "data": "is_muted",
                    "render": function (data) {
                        if (!data) {
                            return '<div class="fa fa-microphone fa-fw green"></div>';
                        } else {
                            return '<div class="fa fa-microphone-slash fa-fw red"></div>';
                        } 
                    }
                },
                {
                    "targets": 8,
                    "data": "is_presenting",
                    "render": function (data) {
                        if (data) {
                            return '<div class="fa fa-bar-chart fa-fw green"></div>';
                        } else {
                            return '<div class="fa fa-bar-chart fa-fw red"></div>';
                        } 
                    }
                },
                {
                    "targets": 9,
                    "data": "is_streaming",
                    "render": function (data) {
                        if (!data) {
                            return '<div class="fa fa-cloud fa-fw black"></div>';
                        } else {
                            return '<div class="fa fa-cloud-upload fa-fw green"></div>';
                        }
                    }
                },
                ],
                "language": {
                    "processing": "Подождите...",
                    "search": "Поиск:",
                    "lengthMenu": "Показать _MENU_ записей",
                    "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
                    "infoEmpty": "Записи с 0 до 0 из 0 записей",
                    "infoFiltered": "(отфильтровано из _MAX_ записей)",
                    "infoPostFix": "",
                    "loadingRecords": "Загрузка записей...",
                    "zeroRecords": "Записи отсутствуют.",
                    "emptyTable": "В таблице отсутствуют данные",
                    "paginate": {
                        "first": "Первая",
                        "previous": "Предыдущая",
                        "next": "Следующая",
                        "last": "Последняя"
                    },
                    "aria": {
                        "sortAscending": ": активировать для сортировки столбца по возрастанию",
                        "sortDescending": ": активировать для сортировки столбца по убыванию"
                    }
                },
                "order": [[4, 'asc']],
                "pageLength": 30
            });
        }
    });
</script>

PepuxFront/Views/Controlpanel/Index_old.cshtml
@using System.ServiceModel.Configuration
@using Microsoft.Ajax.Utilities
@using PepuxFront.Controllers
@model PepuxFront.IpServiceLink.ActiveConfs
<div class="control_grid">
    @(Html.Kendo().Grid<PepuxFront.IpServiceLink.ActiveConfs>
        ()
        .Name("acgrid")

        //.Pdf(m => { m.FileName(AccountController.Uname + "_" + DateTime.Now + ".pdf");
        //m.AllPages();
        //})

        //.Excel(m => { m.FileName(AccountController.Uname + "_" + DateTime.Now + ".xlsx");
        //m.AllPages(true);
        //m.Filterable(true);
        //})

        //.ToolBar(m => { m.Pdf();
        //m.Excel();
        //})

        .DataSource(dataSource => dataSource
            .Ajax()
            .Read(read => read.Action("ActiveConf_Read", "Admin"))
            .AutoSync(true)
            .PageSize(20)
        )
        .Columns(columns =>
        {
            columns.Bound(product => product.name).Title("Название конференции");
            columns.Bound(product => product.start_time2).Title("Время начала");
            columns.Bound(product => product.lock_path).Title("Блокировка").Encoded(false).ClientTemplate(@"<div class='fa fa-unlock fa-fw brand-color k-grid-unlock'></div>").Width(100);
            columns.Bound(i => i.name).Title("Список участников").ClientTemplate(@Html.ActionLink("Участники", "GetParticipants", "Admin", new { confname = "#= name #" }, new { @class = "modal-link btn btn-success" }).ToHtmlString()).Width(250);
            columns.Bound(i => i.name).Title("Управление").ClientTemplate(@Html.ActionLink("Управлять", "Control", "Controlpanel", new { confname = "#= name #", dispname = AccountController.Uname }, new { @class = "modal-link btn btn-success" }).ToHtmlString()).Width(250);

        })

        .Scrollable()

        .Pageable(pageable =>
        {
            pageable.ButtonCount(5);
            pageable.Messages(messages => messages.Display("{0} - {1} из {2} страниц"));
            pageable.Messages(messages => messages.Empty("Нет записей"));
            pageable.Messages(messages => messages.Page("Страница"));
            pageable.Messages(messages => messages.Of("из {0}"));
            pageable.Messages(messages => messages.ItemsPerPage("записей на странице"));
            pageable.Messages(messages => messages.First("Перейти на первую страницу"));
            pageable.Messages(messages => messages.Previous("Перейти на предыдущую страницу"));
            pageable.Messages(messages => messages.Next("Перейти на следующую страницу"));
            pageable.Messages(messages => messages.Last("Перейти на последнюю страницу"));
            pageable.Messages(messages => messages.Refresh("Обновить"));
            pageable.Numeric(true);
            pageable.PreviousNext(true);
        })

        .Sortable()
    )


        </div>
    <script type="text/javascript">

        $(function () {
            setInterval(function () { $("#acgrid").data("kendoGrid").dataSource.fetch(); }, 30000);
        });

    </script>
    <script>
        $(document).ready(function () {
            $("a[href^='http:']:not([href*='" + window.location.host + "'])").each(function () {
                $(this).attr("target", "_blank");
            });
        });

    </script>